spring:
  profiles:
    active: "dev"
  mail:
    test-connection: false      host: smtp.gmail.com
    port: 587
    username: replace_it
    password: replace_it
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    hikari:
      connectionTimeout: 20000 
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/golf 
    username: golf_usr
    password: replace_it
  jpa:
    open-in-view: true  
    show_sql: true
jwt:
  secret: golfBackendSecret
  refresh: refreshSecret
springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  api-docs:
    path: /api  
google:
  recaptcha:
    key:
      site: 6Lf-66YZAAAAAJc3serwf1iRoJg6PgTPJazkfNWD
      secret: ${sm://google_recaptcha_key_secret} 
cors:
  allowedOrigins: dgng.pl
round:
  pageSize: 5
course:
  pageSize: 5
  minSearchLength: 3  
    
---

spring:
  profiles: dev
  mail: 
    properties:
     mail:
      debug: true
  datasource:
    url: jdbc:postgresql://localhost:5432/golf 
  jpa:
    show_sql: true
  liquibase:
    change-log: classpath:/db/dbChangeLog-dev.xml
  cloud:    gcp:      sql:        enabled: false
    
  
---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://10.156.0.3:5432/golf 
  jpa:
    show_sql: false
  liquibase:
    change-log: classpath:/db/dbChangeLog-prod.xml
  cloud:
    gcp:
      sql:
        enabled: false

---

spring:
  profiles: gcp
  datasource:
    url: jdbc:postgresql://10.156.0.3:5432/golf
    password:  ${sm://spring_datasource_password}
  jpa:
    show_sql: false
  liquibase:
    change-log: classpath:/db/dbChangeLog-prod.xml
  mail:
    username: drunkgng@gmail.com
    password: ${sm://spring_mail_password}
  cloud:
    gcp:
      sql:
        enabled: false
        
---

spring:
  profiles: sqlCloud
  datasource:
    password:  ${sm://spring_datasource_password}
  jpa:
    show_sql: false
  liquibase:
    change-log: classpath:/db/dbChangeLog-prod.xml
  mail:
    username: drunkgng@gmail.com
    password: ${sm://spring_mail_password}
  cloud:
    gcp:
      sql:
        enabled: true
        database-name: golf
        instance-connection-name: drunkgolfers:europe-west3:golf-databse

        