spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 5404652492885471
            client-secret: replace_it
            scope:
              - public_profile
        provider:
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=name,first_name,last_name
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  profiles:
    active: "dev"
  mail:
    test-connection: false  
    host: smtp.gmail.com
    port: 587
    username: replace_it
    password: replace_it
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    hikari:
      connectionTimeout: 20000 
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/golf 
    username: golf_usr
    password: replace_it
  jpa:
    open-in-view: true  
    show_sql: true
jwt:
  secret: golfBackendSecret
  refresh: refreshSecret
springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  api-docs:
    path: /api  
google:
  recaptcha:
    key:
      site: 6Lf-66YZAAAAAJc3serwf1iRoJg6PgTPJazkfNWD
      secret: replace_it 
cors:
  allowedOrigins: dgng.pl
round:
  pageSize: 5
course:
  pageSize: 5
  minSearchLength: 3
player:
  tempPwd: welcome
    
---

spring:
  config:
    activate:
      on-profile: dev
  mail: 
    properties:
     mail:
      debug: true
  datasource:
    url: jdbc:postgresql://localhost:5432/golf 
  jpa:
    show_sql: true
  liquibase:
    change-log: classpath:/db/dbChangeLog-dev.xml
oauth2:
  redirect: http://localhost:4200/login

---

spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          facebook:
            redirect-uri: https://dgng.pl/login/oauth2/code/facebook
  datasource:
    url: jdbc:postgresql://10.156.0.3:5432/golf 
  jpa:
    show_sql: false
  liquibase:
    change-log: classpath:/db/dbChangeLog-prod.xml
oauth2:
  redirect: https://www.dgng.pl/login

        