apiVersion: apps/v1
kind: Deployment
metadata:
  name: golf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golf-app
  template:
    metadata:
      labels:
        app: golf-app
    spec:
      containers:
        - name: myapp
          image: gmalewicz/golf-app
          envFrom:
            - configMapRef:
                name: golf-app-configmap
            - secretRef:
                name: golf-app-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            requests:
              memory: "300Mi"
              cpu: "700m"
            limits:
              memory: "800Mi"
              cpu: "700m"
          ports:
            - containerPort: 8080
