# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java GOLF CI with Maven

on:
  push:
    branches: [ master ]
    tags:
     - '**' 
  pull_request:
    branches: [ master ]
    
env:
  VERSION_EXP: git describe --tags --always --first-parent --dirty  
  IMAGE: ${{ github.repository_owner }}/${{ github.event.repository.name }}
  ORGANIZATION: ${{ github.repository_owner }} 
  REGISTRY_HOSTNAME: eu.gcr.io
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
        
    - name: Create log directory
      run: |
        sudo mkdir /home/grzegorz_malewicz
        sudo mkdir /home/grzegorz_malewicz/logs
        
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
                
    - name: Buiild & analyze with SonarCloud
      #run: mvn -B verify sonar:sonar --file ./pom.xml 
      run: mvn -B package --file ./pom.xml
        -Dsonar.organization=gmalewicz 
        -Dsonar.host.url=https://sonarcloud.io 
        -Dsonar.login=$SONAR_TOKEN 
        -Dsonar.projectName=gmalewicz_golf-app
        -Dsonar.java.source=13
        -Dsonar.sources=src/main/java,src/main/resources/templates
        -Dsonar.java.binaries=target/classes
        -Dsonar.sourceEncoding=UTF-8
        -Dsonar.exclusions=.git/**,.settings/**,target/**
          --file ./pom.xml 
      env:
        google_recaptcha_key_site: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
        google_recaptcha_key_secret: ${{secrets.GOOGLE_RECAPTCHA_KEY_SECRET}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        
    - name: Set up Google Cloud SDK
      if: startsWith(github.ref, 'refs/tags/')
      #if: always()
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
      
    - name: Rename the file 
      if: startsWith(github.ref, 'refs/tags/')
      # if: always()
      run: |
        cp ./target/golf-*.jar ./target/golf.jar
      
    - name: Copy build file to Google Cloud Storage
      if: startsWith(github.ref, 'refs/tags/')
      # if: always()
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path:   /home/runner/work/golf-app/golf-app/target/golf.jar
        destination: drungolfersweb
       
#    - name: Set up version
#      if: always()
#      #if: startsWith(github.ref, 'refs/tags/')
#      run: echo "VERSION=$($VERSION_EXP)" >> $GITHUB_ENV   
       
#    - name: Configure docker to use the gcloud command-line tool as a credential helper
#      if: always()
#      run: |
#        # Set up docker to authenticate
#        # via gcloud command-line tool.
#        gcloud auth configure-docker
 
#    - name: Assemble image
#      if: always()
#      #if: startsWith(github.ref, 'refs/tags/')
#      run: docker build -t $IMAGE:$VERSION -t $IMAGE:latest -t "$REGISTRY_HOSTNAME"/"drunkgolfers"/"golf-app":"$VERSION" .
      
#    - name: Publish image
#      if: startsWith(github.ref, 'refs/tags/')
#      #if: always()
#      run: |
#        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u $ORGANIZATION --password-stdin
#        docker push $IMAGE:$VERSION
#        docker push $IMAGE:latest
        
#    - name: Publish
#      if: always()
#      run: |
#        export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
#        echo $TAG
#        docker push "$REGISTRY_HOSTNAME"/"drunkgolfers"/"golf-app":"$VERSION"
#        docker tag "$REGISTRY_HOSTNAME"/"drunkgolfers"/"golf-app":"$VERSION" "$REGISTRY_HOSTNAME"/"drunkgolfers"/"golf-app":latest
#        docker push "$REGISTRY_HOSTNAME"/"drunkgolfers"/"golf-app":latest
